// Script to generate ABI and address files from Hardhat deployments
// Adapted for TimeCapsule contract

import { readFileSync, writeFileSync, existsSync } from "fs";
import { join } from "path";

const deploymentsDir = join(process.cwd(), "..", "contracts", "deployments");
const outputDir = join(process.cwd(), "abi");

// Find all deployment JSON files
// Automatically skips networks that haven't been deployed
function findDeployments() {
  const deployments = {};
  
  // Check localhost
  const localhostDir = join(deploymentsDir, "localhost");
  if (existsSync(localhostDir)) {
    const localhostFile = join(localhostDir, "TimeCapsule.json");
    if (existsSync(localhostFile)) {
      try {
        const deployment = JSON.parse(readFileSync(localhostFile, "utf-8"));
        if (deployment.address) {
          deployments["31337"] = {
            address: deployment.address,
            chainId: 31337,
            chainName: "localhost",
          };
          console.log("  ✓ Found localhost deployment");
        }
      } catch (error) {
        console.log("  ⚠ Skipping localhost deployment (invalid JSON)");
      }
    }
  }

  // Check sepolia (chainId: 11155111)
  const sepoliaDir = join(deploymentsDir, "sepolia");
  if (existsSync(sepoliaDir)) {
    const sepoliaFile = join(sepoliaDir, "TimeCapsule.json");
    if (existsSync(sepoliaFile)) {
      try {
        const deployment = JSON.parse(readFileSync(sepoliaFile, "utf-8"));
        if (deployment.address) {
          deployments["11155111"] = {
            address: deployment.address,
            chainId: 11155111,
            chainName: "sepolia",
          };
          console.log("  ✓ Found sepolia deployment (chainId: 11155111)");
        }
      } catch (error) {
        console.log("  ⚠ Skipping sepolia deployment (invalid JSON)");
      }
    }
  }

  return deployments;
}

// Generate ABI file
function generateABI() {
  // Try to find ABI from artifacts
  const artifactsDir = join(
    process.cwd(),
    "..",
    "contracts",
    "artifacts",
    "contracts",
    "TimeCapsule.sol",
    "TimeCapsule.json"
  );

  let abi = [];
  if (existsSync(artifactsDir)) {
    const artifact = JSON.parse(readFileSync(artifactsDir, "utf-8"));
    abi = artifact.abi;
  }

  const abiContent = `// Auto-generated by genabi.mjs
// DO NOT EDIT MANUALLY

export const TimeCapsuleABI = {
  abi: ${JSON.stringify(abi, null, 2)},
} as const;
`;

  writeFileSync(join(outputDir, "TimeCapsuleABI.ts"), abiContent);
  console.log("✓ Generated TimeCapsuleABI.ts");
}

// Generate addresses file
function generateAddresses() {
  const deployments = findDeployments();

  if (Object.keys(deployments).length === 0) {
    console.log("  ⚠ No deployments found, generating empty addresses file");
  }

  const addressesContent = `// Auto-generated by genabi.mjs
// DO NOT EDIT MANUALLY
// This file contains contract addresses for different networks
// ChainId 11155111 = Sepolia testnet

import { ethers } from "ethers";

export const TimeCapsuleAddresses: Record<
  string,
  {
    address: \`0x\${string}\`;
    chainId: number;
    chainName?: string;
  }
> = ${JSON.stringify(deployments, null, 2)} as const;
`;

  writeFileSync(join(outputDir, "TimeCapsuleAddresses.ts"), addressesContent);
  console.log("✓ Generated TimeCapsuleAddresses.ts");
  console.log(`  Found ${Object.keys(deployments).length} deployment(s)`);
  
  // Show deployed networks
  if (Object.keys(deployments).length > 0) {
    Object.values(deployments).forEach(deployment => {
      console.log(`    - ${deployment.chainName || 'unknown'} (chainId: ${deployment.chainId}): ${deployment.address}`);
    });
  }
}

// Main
try {
  generateABI();
  generateAddresses();
  console.log("✓ ABI generation complete");
} catch (error) {
  console.error("✗ Error generating ABI:", error);
  process.exit(1);
}
