// Auto-generated by genabi.mjs
// DO NOT EDIT MANUALLY
// This file contains contract addresses for different networks
// ChainId 11155111 = Sepolia testnet

import { ethers } from "ethers";

export const TimeCapsuleAddresses: Record<
  string,
  {
    address: `0x${string}`;
    chainId: number;
    chainName?: string;
  }
> = {
  "11155111": {
    "address": "0x6c5404e2eFD90EA936336E0ddCf2d7D7f9B6270e",
    "chainId": 11155111,
    "chainName": "sepolia"
  }
} as const;
