/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface TimeCapsuleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "canUnlock"
      | "capsuleCounter"
      | "capsules"
      | "confidentialProtocolId"
      | "createCapsule"
      | "getCapsuleInfo"
      | "getEncryptedContents"
      | "getTotalCapsules"
      | "getUserCapsules"
      | "unlockCapsule"
      | "userCapsules"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "CapsuleCreated" | "CapsuleUnlocked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "canUnlock",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "capsuleCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "capsules",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createCapsule",
    values: [BytesLike[], BytesLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCapsuleInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedContents",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalCapsules",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserCapsules",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unlockCapsule",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userCapsules",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "canUnlock", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "capsuleCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "capsules", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createCapsule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCapsuleInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedContents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalCapsules",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserCapsules",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unlockCapsule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userCapsules",
    data: BytesLike
  ): Result;
}

export namespace CapsuleCreatedEvent {
  export type InputTuple = [
    capsuleId: BigNumberish,
    owner: AddressLike,
    heir: AddressLike,
    unlockTime: BigNumberish
  ];
  export type OutputTuple = [
    capsuleId: bigint,
    owner: string,
    heir: string,
    unlockTime: bigint
  ];
  export interface OutputObject {
    capsuleId: bigint;
    owner: string;
    heir: string;
    unlockTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CapsuleUnlockedEvent {
  export type InputTuple = [capsuleId: BigNumberish, unlocker: AddressLike];
  export type OutputTuple = [capsuleId: bigint, unlocker: string];
  export interface OutputObject {
    capsuleId: bigint;
    unlocker: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TimeCapsule extends BaseContract {
  connect(runner?: ContractRunner | null): TimeCapsule;
  waitForDeployment(): Promise<this>;

  interface: TimeCapsuleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  canUnlock: TypedContractMethod<[capsuleId: BigNumberish], [boolean], "view">;

  capsuleCounter: TypedContractMethod<[], [bigint], "view">;

  capsules: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, boolean, boolean] & {
        unlockTime: bigint;
        owner: string;
        heir: string;
        exists: boolean;
        unlocked: boolean;
      }
    ],
    "view"
  >;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  createCapsule: TypedContractMethod<
    [
      encryptedContentChunks: BytesLike[],
      inputProof: BytesLike,
      unlockTime: BigNumberish,
      heir: AddressLike
    ],
    [bigint],
    "nonpayable"
  >;

  getCapsuleInfo: TypedContractMethod<
    [capsuleId: BigNumberish],
    [
      [bigint, string, string, boolean, boolean] & {
        unlockTime: bigint;
        owner: string;
        heir: string;
        exists: boolean;
        unlocked: boolean;
      }
    ],
    "view"
  >;

  getEncryptedContents: TypedContractMethod<
    [capsuleId: BigNumberish],
    [string[]],
    "view"
  >;

  getTotalCapsules: TypedContractMethod<[], [bigint], "view">;

  getUserCapsules: TypedContractMethod<[user: AddressLike], [bigint[]], "view">;

  unlockCapsule: TypedContractMethod<
    [capsuleId: BigNumberish],
    [void],
    "nonpayable"
  >;

  userCapsules: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "canUnlock"
  ): TypedContractMethod<[capsuleId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "capsuleCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "capsules"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, boolean, boolean] & {
        unlockTime: bigint;
        owner: string;
        heir: string;
        exists: boolean;
        unlocked: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createCapsule"
  ): TypedContractMethod<
    [
      encryptedContentChunks: BytesLike[],
      inputProof: BytesLike,
      unlockTime: BigNumberish,
      heir: AddressLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getCapsuleInfo"
  ): TypedContractMethod<
    [capsuleId: BigNumberish],
    [
      [bigint, string, string, boolean, boolean] & {
        unlockTime: bigint;
        owner: string;
        heir: string;
        exists: boolean;
        unlocked: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEncryptedContents"
  ): TypedContractMethod<[capsuleId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getTotalCapsules"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserCapsules"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "unlockCapsule"
  ): TypedContractMethod<[capsuleId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userCapsules"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getEvent(
    key: "CapsuleCreated"
  ): TypedContractEvent<
    CapsuleCreatedEvent.InputTuple,
    CapsuleCreatedEvent.OutputTuple,
    CapsuleCreatedEvent.OutputObject
  >;
  getEvent(
    key: "CapsuleUnlocked"
  ): TypedContractEvent<
    CapsuleUnlockedEvent.InputTuple,
    CapsuleUnlockedEvent.OutputTuple,
    CapsuleUnlockedEvent.OutputObject
  >;

  filters: {
    "CapsuleCreated(uint256,address,address,uint256)": TypedContractEvent<
      CapsuleCreatedEvent.InputTuple,
      CapsuleCreatedEvent.OutputTuple,
      CapsuleCreatedEvent.OutputObject
    >;
    CapsuleCreated: TypedContractEvent<
      CapsuleCreatedEvent.InputTuple,
      CapsuleCreatedEvent.OutputTuple,
      CapsuleCreatedEvent.OutputObject
    >;

    "CapsuleUnlocked(uint256,address)": TypedContractEvent<
      CapsuleUnlockedEvent.InputTuple,
      CapsuleUnlockedEvent.OutputTuple,
      CapsuleUnlockedEvent.OutputObject
    >;
    CapsuleUnlocked: TypedContractEvent<
      CapsuleUnlockedEvent.InputTuple,
      CapsuleUnlockedEvent.OutputTuple,
      CapsuleUnlockedEvent.OutputObject
    >;
  };
}
